POST http://localhost:3000/address
Content-Type: application/json

{
    "address":"Rua Teste Simões",
    "number":"449",
    "cep":"02504000",
    "city":"São Paulo",
    "state":"SP",
    "country":"BR"
}

### FIND ALL
GET http://localhost:3000/address
### FIND ONE
GET http://localhost:3000/users/2
### UPDATE
PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "email":"teste.teste1@gmail.com",
    "name":"Usuário 1",
    "age":"24",
    "telephone":"1199955545"
}
### DELETE
DELETE http://localhost:3000/users/1